# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Category.create([
    { 
        category: "GENERAL",
    },
    { 
        category: "ADVICE",
    },
    { 
        category: "MEET & GREET",
    },
]);


# The rest are optional, giving us some data to play around with
User.create([ 
  { 
    username: "Zi Xin",
    password: "12345",
    bio: "Hi, I am the first user on this site",
    country: "SG",
  },
  { 
    username: "Tommy the Cat",
    password: "12345",
    bio: "Hi, all my posts and comments are generated by chatgpt",
    country: "US",
  },
  { 
    username: "Georgia Albraca",
    password: "12345",
    bio: "My dream is to get into Hollywood",
    country: "GB",
  },
  { 
    username: "Ollie",
    password: "12345",
    bio: "I am a maltese and I hate humans",
    country: "SG",
  },
  { 
    username: "Mao Mao",
    password: "12345",
    bio: "My favourite colour is grey and I love to sleep",
    country: "NL",
  },
  
]);


MainThread.create([ 
  { 
    title: "Hello World!",
    body: "The first ever thread!",
    category_id: 1,
    user_id: 1

  },
  { 
    title: "Why grey is the best colour",
    body: "Grey is the epitome of versatility and sophistication, making it the best color. Its neutral nature seamlessly complements any palette, serving as an ideal backdrop for bold accents or understated elegance. Grey exudes timeless charm, effortlessly adapting to diverse aesthetics and styles. In fashion, interiors, and design, its understated allure allows other colors to shine. Symbolizing balance and neutrality, grey is a calming force in a hectic world. It conveys a sense of maturity and wisdom, transcending fleeting trends. Whether in subtle tones or bold shades, grey stands as a timeless, adaptable hue, making it the unequivocal champion of the color spectrum.",
    category_id: 1,
    user_id: 5
  },
  { 
    title: "My experience at MIT",
    body: "As a student at MIT, each day is a dynamic fusion of intellectual stimulation and hands-on exploration. Surrounded by brilliant minds and cutting-edge technology, my academic journey is a relentless pursuit of knowledge. From mind-bending lectures to collaborative problem-solving sessions, the atmosphere fosters creativity and innovation. Late nights in state-of-the-art laboratories and engaging discussions in iconic Infinite Corridor fuel my passion for learning. The camaraderie among diverse, driven peers creates a unique synergy, pushing boundaries and redefining what's possible. MIT's ethos of pushing the envelope resonates in every project, class, and conversation, shaping me into a resilient and inventive thinker.",
    category_id: 1,
    user_id: 2
  },
  { 
    title: "Hey anyone want to be friends?",
    body: "Looking for something casual",
    category_id: 3,
    user_id: 2
  },
]);

Comment.create([
    { 
        body: "Hello!",
        main_thread_id: 1,
        user_id: 3
    },
    { 
        body: "Bye",
        main_thread_id: 1,
        user_id: 4
    },
    { 
        body: "No",
        main_thread_id: 4,
        user_id: 4
    },
    { 
        body: "Nah white is cooler",
        main_thread_id: 2,
        user_id: 4
    },
    { 
        body: "My rabbit is grey in colour, so +1 like to you!",
        main_thread_id: 2,
        user_id: 1
    },
    { 
        body: "Indeed! I have been to MIT and it is a nice place. 100% Recommend it.",
        main_thread_id: 3,
        user_id: 3
    },
]);

Like.create([
    { 
        main_thread_id: 2,
        user_id: 1
    },
    { 
        main_thread_id: 2,
        user_id: 2
    },
    { 
        main_thread_id: 2,
        user_id: 3
    },
    { 
        main_thread_id: 2,
        user_id: 5
    },
    { 
        main_thread_id: 2,
        user_id: 2
    },
]);
